export const kernels = {
  state_compute: {
    uniform: 'GateParams',
    wgsl: 'GateParams',
    bindings: ['stateA:r', 'stateB:rw', 'uniform:u', 'measurement:r'],
    workgroup: 64,
  },
  measure_reduce: {
    uniform: 'MeasureReduceParams',
    wgsl: 'MeasureReduceParams',
    bindings: ['stateA:r', 'measurement:rw', 'uniform:u'],
    workgroup: 64,
  },
  measure_collapse: {
    uniform: 'MeasureCollapseParams',
    wgsl: 'MeasureCollapseParams',
    bindings: ['stateA:r', 'stateB:rw', 'measurement:r', 'uniform:u'],
    workgroup: 64,
  },
  probability_reduce: {
    uniform: 'ProbabilityReduceParams',
    wgsl: 'ProbabilityReduceParams',
    bindings: ['stateA:r', 'probability:rw', 'uniform:u'],
    workgroup: 64,
  },
  probability_normalize: {
    uniform: 'ProbabilityReduceParams',
    wgsl: 'ProbabilityReduceParams',
    bindings: ['probability:rw', 'uniform:u'],
    workgroup: 64,
  },
  probability_aggregate: {
    uniform: null,
    wgsl: null,
    bindings: ['probability:r', 'aggregate:rw', 'instances:r'],
    workgroup: 64,
  },
  bloch_reduce: {
    uniform: 'BlochParams',
    wgsl: 'BlochParams',
    bindings: ['stateA:r', 'bloch:rw', 'uniform:u'],
    workgroup: 64,
  },
  amplitude_capture: {
    uniform: 'AmplitudeCaptureParams',
    wgsl: 'Params',
    bindings: ['stateA:r', 'amplitude:rw', 'amplitudeMeta:rw', 'uniform:u'],
    workgroup: 1,
  },
  density_capture: {
    uniform: 'DensityCaptureParams',
    wgsl: 'DensityCaptureParams',
    bindings: ['stateA:r', 'density:rw', 'densityMeta:rw', 'uniform:u'],
    workgroup: 64,
  },
} as const
export const bindingNames: Record<string, string[]> = {
  stateA: ['state_in', 'state'],
  stateB: ['state_out'],
  measurement: ['aux_out', 'aux'],
  probability: ['probability_out', 'probability_data'],
  aggregate: ['aggregate_out'],
  instances: ['instances'],
  bloch: ['bloch_out'],
  amplitude: ['amplitude_data'],
  amplitudeMeta: ['amplitude_meta'],
  density: ['density_data'],
  densityMeta: ['density_meta'],
  uniform: ['params'],
}
export const bindingTypes: Record<string, string> = {
  stateA: 'array<vec2<f32>>',
  stateB: 'array<vec2<f32>>',
  measurement: 'array<vec4<f32>>',
  probability: 'array<f32>',
  aggregate: 'array<f32>',
  instances: 'array<ProbabilityInstance>',
  bloch: 'array<vec4<f32>>',
  amplitude: 'array<f32>',
  amplitudeMeta: 'array<vec4<f32>>',
  density: 'array<vec2<f32>>',
  densityMeta: 'array<vec4<f32>>',
}
export type Kernel = keyof typeof kernels
export const constants = {
  state_compute: { UNCONDITIONAL: 'GATE_UNCONDITIONAL' },
  probability_reduce: { MAX_PROBABILITY_OUTCOMES: 'MAX_PROBABILITY_OUTCOMES' },
  probability_normalize: { MAX_PROBABILITY_OUTCOMES: 'MAX_PROBABILITY_OUTCOMES' },
  probability_aggregate: {
    MAX_PROBABILITY_OUTCOMES: 'MAX_PROBABILITY_OUTCOMES',
    MAX_PROBABILITY_AGGREGATE_ROWS: 'MAX_PROBABILITY_AGGREGATE_ROWS',
    PROBABILITY_AGGREGATE_MIN_SPAN: 'PROBABILITY_AGGREGATE_MIN_SPAN',
    PROBABILITY_RENDER_MODE_SAMPLE: 'PROBABILITY_RENDER_MODE_SAMPLE',
    PROBABILITY_RENDER_MODE_PLACEHOLDER: 'PROBABILITY_RENDER_MODE_PLACEHOLDER',
  },
  amplitude_capture: { MAX_OUTCOMES: 'MAX_AMPLITUDE_OUTCOMES', VALUES_PER_SLOT: 'AMPLITUDE_VALUES_PER_SLOT' },
  density_capture: { MAX_DENSITY_CELLS: 'DENSITY_VALUES_PER_SLOT' },
} as const
export const fingerprints: [string, string, number][] = [
  ['gpu/recompute/pack.rs', 'let rest_count = (state_count as u32) >> *span;', 1],
  ['gpu/recompute/pack.rs', 'seed: gate_id.as_u32(),', 1],
  ['gpu/recompute/pack.rs', 'let total_qubits = usize::BITS - state_count.leading_zeros() - 1;', 1],
  ['gpu/recompute/pack.rs', 'phase_lock_enabled: u32::from(*span != total_qubits),', 1],
  ['gpu/recompute/dispatch.rs', 'let dispatch_x = outcomes.min(256);', 1],
  ['gpu/recompute/dispatch.rs', 'let dispatch_y = outcomes.div_ceil(dispatch_x);', 1],
  ['gpu/recompute/dispatch.rs', 'pass.dispatch_workgroups(cells.div_ceil(64), 1, 1);', 1],
  ['gpu/recompute/dispatch.rs', 'self.in_index = 1 - self.in_index;', 2],
  ['gpu/recompute.rs', 'let dispatch_x = pair_count.div_ceil(STATE_WORKGROUP_SIZE);', 1],
  ['gpu/recompute/clear.rs', `encoder.copy_buffer_to_buffer(
&resources.common.state_seed_buffer,
0,
&resources.common.state_buffers[0],
0,
std::mem::size_of::<[f32; 2]>() as wgpu::BufferAddress,
);`, 1],
  ['gpu/recompute/pack.rs', 'if pair_count == 0 {', 1],
  ['gpu/recompute/dispatch.rs', 'pass.dispatch_workgroups(self.dispatch_x, 1, 1);', 2],
  ['gpu/recompute/dispatch.rs', 'let outcomes = 1u32 << span;', 1],
  ['gpu/recompute/dispatch.rs', 'let cells = 1u32 << (span * 2);', 1],
  ['gates/params.rs', 'pub(crate) const GATE_MODE_WRITE0: u32 = 1;', 1],
  ['gates/params.rs', 'pub(crate) const GATE_MODE_WRITE1: u32 = 2;', 1],
  ['gpu/callbacks/probability_display.rs', '&& instance.span >= PROBABILITY_AGGREGATE_MIN_SPAN', 1],
  ['gpu/callbacks/probability_display.rs', '(MAX_PROBABILITY_AGGREGATE_ROWS as u32).div_ceil(64),', 1],
]
