import fs from 'node:fs'
import path from 'node:path'

const EXPORT_NAMES = [
  'REM',
  'STATE_CIRCLE_BOTTOM_MARGIN',
  'STATE_HANDLE_HEIGHT',
  'STATE_VIEWPORT_DEFAULT_WIDTH',
  'STATE_VIEWPORT_DEFAULT_HEIGHT',
  'STATE_VIEWPORT_MIN_WIDTH',
  'STATE_VIEWPORT_MIN_HEIGHT',
  'STATE_VIEWPORT_MAX_WIDTH',
  'STATE_VIEWPORT_MAX_HEIGHT',
  'STATE_PANEL_CORNER_RADIUS',
  'STATE_RESIZE_HANDLE_PAD',
  'STATE_RESIZE_HANDLE_STROKE',
  'STATE_RESIZE_HIT_PAD',
  'LOCAL_MAX_QUBITS',
  'GPU_MAX_QUBITS',
  'MAX_QUBITS',
  'PALETTE_CIRCUIT_GAP',
  'LINE_Y',
  'LINE_GAP',
  'CIRCUIT_PADDING',
  'QUBIT_LABEL_WIDTH',
  'QUBIT_LABEL_GAP',
  'LINE_LEFT_OFFSET',
  'LINE_RIGHT_OFFSET',
  'GATE_SIZE',
  'SLOT_SPACING',
  'SNAP_DISTANCE',
  'PALETTE_SIZE',
  'PALETTE_GAP',
  'PALETTE_ROW_GAP',
  'PALETTE_PADDING_X',
  'PALETTE_PADDING_Y',
  'PALETTE_CORNER_RADIUS',
  'PALETTE_ROW_Y',
] as const

type ConstantName = typeof EXPORT_NAMES[number]

const repoRoot = path.resolve(__dirname, '..')
const rustConstantsPath = path.join(repoRoot, 'src/constants.rs')
const outputPath = path.join(repoRoot, 'test-support/generated-ui-constants.ts')

const stripComments = (source: string): string => source.replace(/\/\/.*$/gm, '')

const parseRustConstants = (source: string): Map<string, string> => {
  const constants = new Map<string, string>()
  const matcher = /pub\(crate\) const ([A-Z0-9_]+): [^=]+ = ([\s\S]*?);/g
  let match: RegExpExecArray | null
  while ((match = matcher.exec(source)) !== null) {
    constants.set(match[1], stripComments(match[2]).trim())
  }
  return constants
}

const toJavaScriptExpression = (expression: string): string => {
  const jsExpression = expression.replace(/\b([0-9]+)\.0\b/g, '$1')
  if (!/^[A-Z0-9_\s.+\-*/()<]+$/.test(jsExpression)) {
    throw new Error(`unsupported constant expression: ${expression}`)
  }
  return jsExpression
}

const evaluateConstants = (expressions: Map<string, string>): Record<string, number> => {
  const values: Record<string, number> = {}
  const pending = new Map(expressions)

  while (pending.size > 0) {
    let progressed = false
    for (const [name, expression] of pending) {
      const identifiers = [...expression.matchAll(/\b[A-Z][A-Z0-9_]*\b/g)].map((match) => match[0])
      if (!identifiers.every((identifier) => identifier in values)) {
        continue
      }
      const args = Object.keys(values)
      const fn = new Function(...args, `return (${toJavaScriptExpression(expression)})`) as (...args: number[]) => number
      values[name] = fn(...args.map((arg) => values[arg]))
      pending.delete(name)
      progressed = true
    }
    if (!progressed) {
      throw new Error(`unable to resolve constants: ${[...pending.keys()].join(', ')}`)
    }
  }

  return values
}

const render = (values: Record<ConstantName, number>): string => {
  const lines = EXPORT_NAMES.map((name) => `  ${name}: ${Number(values[name].toFixed(6))},`)
  return `// Generated by scripts/generate-ui-constants.ts from src/constants.rs. Do not edit.\n\nexport const UI_CONSTANTS = {\n${lines.join('\n')}\n} as const\n\nexport type UiConstantName = keyof typeof UI_CONSTANTS\n`
}

const main = (): void => {
  const values = evaluateConstants(parseRustConstants(fs.readFileSync(rustConstantsPath, 'utf8')))
  const missing = EXPORT_NAMES.filter((name) => !(name in values))
  if (missing.length > 0) {
    throw new Error(`missing Rust constants: ${missing.join(', ')}`)
  }

  const output = render(values as Record<ConstantName, number>)
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf8') : ''
    if (current !== output) {
      throw new Error('generated UI constants are out of date; run pnpm run generate:ui-constants')
    }
    return
  }
  fs.writeFileSync(outputPath, output)
}

main()
